{"name": "test_wrong_pwd", "status": "passed", "description": "密码输入6次错误", "attachments": [{"name": "log", "source": "4ff34d28-1056-471e-a2e2-951da693528a-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "b4d61154-8deb-4281-a8ac-5d0b84d6f54f-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "e8db239e-af21-487c-b088-cce33289a422-attachment.txt", "type": "text/plain"}], "start": 1632469964675, "stop": 1632469972070, "uuid": "588eb0e3-7336-48db-9b2c-32f54845a678", "historyId": "7b9480ebb1961c7c14cb69cc7e65ba50", "testCaseId": "e4c5762512a76c681290f066bcc0e861", "fullName": "test_case.Login_case.TestLogin#test_wrong_pwd", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "story", "value": "参数填写不正确，登录失败"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "Login_case"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-KSOAST3"}, {"name": "thread", "value": "21308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.Login_case"}]}