{"name": "test_wrong_pwd", "status": "passed", "description": "密码输入6次错误", "attachments": [{"name": "log", "source": "9f9f81e3-96f4-453f-ac76-6af1f133f3c6-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "9e06801e-8658-4f8a-8204-dd83b604a320-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "ff206b61-68cf-4591-bc85-65d3b3d49e64-attachment.txt", "type": "text/plain"}], "start": 1632454820191, "stop": 1632454821618, "uuid": "6f6ce370-62ad-4232-b9f9-274c51ec619c", "historyId": "7b9480ebb1961c7c14cb69cc7e65ba50", "testCaseId": "e4c5762512a76c681290f066bcc0e861", "fullName": "test_case.Login_case.TestLogin#test_wrong_pwd", "labels": [{"name": "story", "value": "参数填写不正确，登录失败"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "Login_case"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-KSOAST3"}, {"name": "thread", "value": "18736-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.Login_case"}]}