{"name": "test_wrong_pwd", "status": "passed", "description": "密码输入6次错误", "attachments": [{"name": "log", "source": "371c6394-a6db-4daa-af31-ef796d693fa7-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "bf8759be-5458-409f-a7cc-bb2d9c51e6a7-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "66cc1354-a60a-406c-a9a4-8c8ab3293fbb-attachment.txt", "type": "text/plain"}], "start": 1632468360528, "stop": 1632468361871, "uuid": "50a254b8-489a-4781-8659-9509ef8cd5ab", "historyId": "7b9480ebb1961c7c14cb69cc7e65ba50", "testCaseId": "e4c5762512a76c681290f066bcc0e861", "fullName": "test_case.Login_case.TestLogin#test_wrong_pwd", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "story", "value": "参数填写不正确，登录失败"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "Login_case"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-KSOAST3"}, {"name": "thread", "value": "7292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.Login_case"}]}