Fri, 24 Sep 2021 11:12:05-run_all_case.py-Register_case.py-[line:237]-INFO-[日志信息]: 开始执行脚本test_CodeError：

