{"name": "test_wrong_pwd", "status": "passed", "description": "密码输入6次错误", "attachments": [{"name": "log", "source": "ce1975e8-4757-4135-b0c6-fb4f70e1555a-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "42e6ee8e-9037-4248-abe9-ccbcb8af273e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "823c1996-ff4f-44fa-b33a-450fba7f6d77-attachment.txt", "type": "text/plain"}], "start": 1632473705943, "stop": 1632473713275, "uuid": "949d8b0b-9981-4ecd-b601-e666805ea67a", "historyId": "7b9480ebb1961c7c14cb69cc7e65ba50", "testCaseId": "e4c5762512a76c681290f066bcc0e861", "fullName": "test_case.Login_case.TestLogin#test_wrong_pwd", "labels": [{"name": "story", "value": "参数填写不正确，登录失败"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "Login_case"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-KSOAST3"}, {"name": "thread", "value": "24288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.Login_case"}]}