Wed, 12 Jan 2022 11:18:33-login-Assert.py-[line:47]-INFO-[日志信息]: Response body msg == expected_msg, expected_msg is ,body_msg is  
Wed, 12 Jan 2022 11:18:33-login-Assert.py-[line:50]-ERROR-[日志信息]: Response body msg != expected_msg, expected_msg is ,body_msg is 手机号或密码错误，请重试 
Wed, 12 Jan 2022 11:18:34-login-Assert.py-[line:50]-ERROR-[日志信息]: Response body msg != expected_msg, expected_msg is ,body_msg is 手机号或密码错误，请重试 
Wed, 12 Jan 2022 11:18:34-login-Assert.py-[line:50]-ERROR-[日志信息]: Response body msg != expected_msg, expected_msg is ,body_msg is 手机号或密码错误，请重试 
Wed, 12 Jan 2022 14:51:29-__main__-Logs.py-[line:68]-DEBUG-[日志信息]: I am a debug message
Wed, 12 Jan 2022 14:51:29-__main__-Logs.py-[line:69]-INFO-[日志信息]: I am a info message
Wed, 12 Jan 2022 14:51:29-__main__-Logs.py-[line:70]-WARNING-[日志信息]: I am a warning message
Wed, 12 Jan 2022 14:51:29-__main__-Logs.py-[line:71]-ERROR-[日志信息]: I am a error message
Wed, 12 Jan 2022 14:51:29-__main__-Logs.py-[line:72]-CRITICAL-[日志信息]: I am a critical message
Wed, 12 Jan 2022 16:43:49-__main__-Logs.py-[line:67]-DEBUG-[日志信息]: I am a debug message
Wed, 12 Jan 2022 16:43:49-__main__-Logs.py-[line:68]-INFO-[日志信息]: I am a info message
Wed, 12 Jan 2022 16:43:49-__main__-Logs.py-[line:69]-WARNING-[日志信息]: I am a warning message
Wed, 12 Jan 2022 16:43:49-__main__-Logs.py-[line:70]-ERROR-[日志信息]: I am a error message
Wed, 12 Jan 2022 16:43:49-__main__-Logs.py-[line:71]-CRITICAL-[日志信息]: I am a critical message
Wed, 12 Jan 2022 16:55:00-__main__-Logs.py-[line:67]-DEBUG-[日志信息]: I am a debug message
Wed, 12 Jan 2022 16:55:00-__main__-Logs.py-[line:68]-INFO-[日志信息]: I am a info message
Wed, 12 Jan 2022 16:55:00-__main__-Logs.py-[line:69]-WARNING-[日志信息]: I am a warning message
Wed, 12 Jan 2022 16:55:00-__main__-Logs.py-[line:70]-ERROR-[日志信息]: I am a error message
Wed, 12 Jan 2022 16:55:00-__main__-Logs.py-[line:71]-CRITICAL-[日志信息]: I am a critical message
Wed, 12 Jan 2022 17:03:15-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: inBody:
Wed, 12 Jan 2022 17:03:15-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：
Wed, 12 Jan 2022 17:03:15-_jb_pytest_runner.py-test_LoginCase.py-[line:35]-INFO-[日志信息]: 实际返回：
Wed, 12 Jan 2022 17:03:15-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: inBody:
Wed, 12 Jan 2022 17:03:15-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：
Wed, 12 Jan 2022 17:03:16-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: inBody:
Wed, 12 Jan 2022 17:03:16-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：
Wed, 12 Jan 2022 17:03:16-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: inBody:
Wed, 12 Jan 2022 17:03:16-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：
Wed, 12 Jan 2022 17:04:26-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: inBody:
Wed, 12 Jan 2022 17:04:26-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：
Wed, 12 Jan 2022 17:04:26-_jb_pytest_runner.py-test_LoginCase.py-[line:35]-INFO-[日志信息]: 实际返回：
Wed, 12 Jan 2022 17:04:26-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: inBody:
Wed, 12 Jan 2022 17:04:26-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：
Wed, 12 Jan 2022 17:04:26-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: inBody:
Wed, 12 Jan 2022 17:04:26-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：
Wed, 12 Jan 2022 17:04:26-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: inBody:
Wed, 12 Jan 2022 17:04:26-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：
Wed, 12 Jan 2022 17:06:25-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: inBody：{'phone': '18801053303', 'password': 'a753c776ff3ed4fefa2af948af87448910153281', 'captcha_id': '111'}
Wed, 12 Jan 2022 17:06:25-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：{'code': 200, 'msg': ''}
Wed, 12 Jan 2022 17:06:25-_jb_pytest_runner.py-test_LoginCase.py-[line:35]-INFO-[日志信息]: 实际返回：{'ticket': 'd95o2uzYI7q7tY7bHI4U1xBug7s=', 'user': {'id': 3, 'created_at': '2021-08-06T21:36:59+08:00', 'updated_at': '2021-09-14T10:40:09+08:00', 'uuid': '487686b5-637f-4d99-8202-7c0b29fa322d', 'username': 'zty_tester', 'nickname': 'ZhangTy', 'status': 'normal', 'logged_in_at': '2022-01-12T17:04:25.07+08:00', 'email': '', 'phone': '18801053303', 'is_admin': False, 'is_super_admin': False, 'sha1_password': 'a753c776ff3ed4fefa2af948af87448910153281', 'email_confirmed': False, 'idle_job_authority': True, 'mount_net_disk_authority': True, 'invitation_code': '', 'open_id': '111', 'avatar_id': 0, 'register_ip': '', 'growth_value': -251000, 'member_level': 'normal_user', 'level_acq_mode': 'vip_user_acquire', 'member_dateline': None}}
Wed, 12 Jan 2022 17:06:25-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: inBody：{'phone': '18801053303', 'password': '40bd001563085fc35165329ea1ff5c5ecbdbbeef'}
Wed, 12 Jan 2022 17:06:25-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：{'code': 200, 'msg': '手机号或密码错误，请重试'}
Wed, 12 Jan 2022 17:06:25-_jb_pytest_runner.py-test_LoginCase.py-[line:35]-INFO-[日志信息]: 实际返回：1
Wed, 12 Jan 2022 17:06:25-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: inBody：{'phone': '188010533', 'password': 'a753c776ff3ed4fefa2af948af87448910153281'}
Wed, 12 Jan 2022 17:06:25-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：{'code': 200, 'msg': '手机号或密码错误，请重试'}
Wed, 12 Jan 2022 17:06:25-_jb_pytest_runner.py-test_LoginCase.py-[line:35]-INFO-[日志信息]: 实际返回：3
Wed, 12 Jan 2022 17:06:25-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: inBody：{'phone': '18801053124', 'password': 'a8ef6091e7aded9675e79ff635ffd80e8c780420'}
Wed, 12 Jan 2022 17:06:25-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：{'code': 200, 'msg': '手机号或密码错误，请重试'}
Wed, 12 Jan 2022 17:06:25-_jb_pytest_runner.py-test_LoginCase.py-[line:35]-INFO-[日志信息]: 实际返回：3
Wed, 12 Jan 2022 17:08:49-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: 请求参数：{'phone': '18801053303', 'password': 'a753c776ff3ed4fefa2af948af87448910153281', 'captcha_id': '111'}
Wed, 12 Jan 2022 17:08:49-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：{'code': 200, 'msg': ''}
Wed, 12 Jan 2022 17:08:49-_jb_pytest_runner.py-test_LoginCase.py-[line:35]-INFO-[日志信息]: 实际返回：{'ticket': 'd95o2uzYI7q7tY7bHI4U1xBug7s=', 'user': {'id': 3, 'created_at': '2021-08-06T21:36:59+08:00', 'updated_at': '2021-09-14T10:40:09+08:00', 'uuid': '487686b5-637f-4d99-8202-7c0b29fa322d', 'username': 'zty_tester', 'nickname': 'ZhangTy', 'status': 'normal', 'logged_in_at': '2022-01-12T17:06:23.876+08:00', 'email': '', 'phone': '18801053303', 'is_admin': False, 'is_super_admin': False, 'sha1_password': 'a753c776ff3ed4fefa2af948af87448910153281', 'email_confirmed': False, 'idle_job_authority': True, 'mount_net_disk_authority': True, 'invitation_code': '', 'open_id': '111', 'avatar_id': 0, 'register_ip': '', 'growth_value': -251000, 'member_level': 'normal_user', 'level_acq_mode': 'vip_user_acquire', 'member_dateline': None}}
Wed, 12 Jan 2022 17:08:49-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: 请求参数：{'phone': '18801053303', 'password': '40bd001563085fc35165329ea1ff5c5ecbdbbeef'}
Wed, 12 Jan 2022 17:08:49-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：{'code': 200, 'msg': '手机号或密码错误，请重试'}
Wed, 12 Jan 2022 17:08:49-_jb_pytest_runner.py-test_LoginCase.py-[line:35]-INFO-[日志信息]: 实际返回：1
Wed, 12 Jan 2022 17:08:49-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: 请求参数：{'phone': '188010533', 'password': 'a753c776ff3ed4fefa2af948af87448910153281'}
Wed, 12 Jan 2022 17:08:49-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：{'code': 200, 'msg': '手机号或密码错误，请重试'}
Wed, 12 Jan 2022 17:08:49-_jb_pytest_runner.py-test_LoginCase.py-[line:35]-INFO-[日志信息]: 实际返回：4
Wed, 12 Jan 2022 17:08:50-_jb_pytest_runner.py-test_LoginCase.py-[line:30]-INFO-[日志信息]: 请求参数：{'phone': '18801053124', 'password': 'a8ef6091e7aded9675e79ff635ffd80e8c780420'}
Wed, 12 Jan 2022 17:08:50-_jb_pytest_runner.py-test_LoginCase.py-[line:32]-INFO-[日志信息]: 预期返回：{'code': 200, 'msg': '手机号或密码错误，请重试'}
Wed, 12 Jan 2022 17:08:50-_jb_pytest_runner.py-test_LoginCase.py-[line:35]-INFO-[日志信息]: 实际返回：4
Wed, 12 Jan 2022 17:53:28-_jb_pytest_runner.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['conde'] == respData['code']
KeyError: 'conde'

Wed, 12 Jan 2022 17:53:29-_jb_pytest_runner.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['conde'] == respData['code']
KeyError: 'conde'

Wed, 12 Jan 2022 17:53:29-_jb_pytest_runner.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['conde'] == respData['code']
KeyError: 'conde'

Wed, 12 Jan 2022 17:53:29-_jb_pytest_runner.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['conde'] == respData['code']
KeyError: 'conde'

Wed, 12 Jan 2022 17:53:44-_jb_pytest_runner.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'Success' == 200

Wed, 12 Jan 2022 17:53:44-_jb_pytest_runner.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'RequestParameterIsWrong' == 200

Wed, 12 Jan 2022 17:53:44-_jb_pytest_runner.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'RequestParameterIsWrong' == 200

Wed, 12 Jan 2022 17:53:44-_jb_pytest_runner.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'RequestParameterIsWrong' == 200

Wed, 12 Jan 2022 18:05:52-_jb_pytest_runner.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'Success' == 200

Wed, 12 Jan 2022 18:05:52-_jb_pytest_runner.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'RequestParameterIsWrong' == 200

Wed, 12 Jan 2022 18:05:52-_jb_pytest_runner.py-Assert.py-[line:110]-ERROR-[日志信息]: Traceback (most recent call last):
  File "C:\Users\张铁瀛\PycharmProjects\API_AUTO\common\Assert.py", line 104, in define_assert
    assert res['code'] == respData['code']
AssertionError: assert 'AlreadyExist' == 200

Wed, 12 Jan 2022 18:08:09-_jb_pytest_runner.py-test_InstanceCase.py-[line:32]-INFO-[日志信息]: inBody:
Wed, 12 Jan 2022 18:08:09-_jb_pytest_runner.py-test_InstanceCase.py-[line:34]-INFO-[日志信息]: expData:
Wed, 12 Jan 2022 18:08:10-_jb_pytest_runner.py-test_InstanceCase.py-[line:32]-INFO-[日志信息]: inBody:
Wed, 12 Jan 2022 18:08:10-_jb_pytest_runner.py-test_InstanceCase.py-[line:34]-INFO-[日志信息]: expData:
Wed, 12 Jan 2022 18:08:29-_jb_pytest_runner.py-test_InstanceCase.py-[line:32]-INFO-[日志信息]: inBody:
Wed, 12 Jan 2022 18:08:29-_jb_pytest_runner.py-test_InstanceCase.py-[line:34]-INFO-[日志信息]: expData:
Wed, 12 Jan 2022 18:08:31-_jb_pytest_runner.py-test_InstanceCase.py-[line:32]-INFO-[日志信息]: inBody:
Wed, 12 Jan 2022 18:08:31-_jb_pytest_runner.py-test_InstanceCase.py-[line:34]-INFO-[日志信息]: expData:
Wed, 12 Jan 2022 18:15:14-run_all_case.py-run_all_case.py-[line:19]-INFO-[日志信息]: ==================================2022-01-12 18:15:14===================================
Wed, 12 Jan 2022 18:36:50-run_all_case.py-run_all_case.py-[line:19]-INFO-[日志信息]: ==================================2022-01-12 18:36:50===================================
Wed, 12 Jan 2022 18:37:51-run_all_case.py-run_all_case.py-[line:19]-INFO-[日志信息]: ==================================2022-01-12 18:37:51===================================
Wed, 12 Jan 2022 18:38:49-run_all_case.py-run_all_case.py-[line:19]-INFO-[日志信息]: ==================================2022-01-12 18:38:49===================================
